// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cta: dynamic(() => import("./Cta")),
  fun_fact: dynamic(() => import("./FunFact")),
  hero: dynamic(() => import("./Hero")),
  logo_list: dynamic(() => import("./LogoList")),
  separator: dynamic(() => import("./Separator")),
  solutions_summary: dynamic(() => import("./SolutionsSummary")),
  work_with_us: dynamic(() => import("./WorkWithUs")),
};
